<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>net.hnt8.advancedban</groupId>
        <artifactId>Avesban</artifactId>
        <version>4.0.0</version>
    </parent>

    <artifactId>Avesban-BackendLink</artifactId>
    <packaging>jar</packaging>

    <repositories>
        <!-- Spigot API -->
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>luckperms</id>
            <url>https://repo.luckperms.net/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.20-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>net.md-5</groupId>
                    <artifactId>bungeecord-chat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>net.luckperms</groupId>
            <artifactId>api</artifactId>
            <version>5.4</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>net.hnt8.advancedban</groupId>
            <artifactId>Avesban-Core</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>4.4.8</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
                    <finalName>${project.artifactId}-${project.version}-${build}</finalName>
                    <artifactSet>
                        <excludes>
                            <exclude>com.google.code.gson:gson</exclude>
                            <exclude>com.google.errorprone:error_prone_annotations</exclude>
                        </excludes>
                    </artifactSet>
                    <filters>
                        <filter>
                            <artifact>net.hnt8.advancedban:Avesban-BackendLink</artifact>
                            <includes>
                                <include>**</include>
                            </includes>
                        </filter>
                        <filter>
                            <artifact>net.hnt8.advancedban:Avesban-Core</artifact>
                            <includes>
                                <include>net/hnt8/advancedban/redis/**</include>
                                <include>net/hnt8/advancedban/utils/ConfigMigrator*</include>
                                <include>net/hnt8/advancedban/utils/YamlColonQuoter*</include>
                            </includes>
                        </filter>
                    </filters>
                    <relocations>
                        <relocation>
                            <pattern>redis.clients.jedis</pattern>
                            <shadedPattern>${project.groupId}.shaded.redis.clients.jedis</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>redis.clients.authentication</pattern>
                            <shadedPattern>${project.groupId}.shaded.redis.clients.authentication</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.apache.commons.pool2</pattern>
                            <shadedPattern>${project.groupId}.shaded.org.apache.commons.pool2</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>net.minidev</pattern>
                            <shadedPattern>${project.groupId}.shaded.net.minidev</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.json</pattern>
                            <shadedPattern>${project.groupId}.shaded.org.json</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.slf4j</pattern>
                            <shadedPattern>${project.groupId}.shaded.org.slf4j</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
